import { unindent } from "@goodbyenjn/utils";
import { Volume as BaseVolume } from "memfs";

import type { Pm } from "@/types";

interface VFile {
    name: string;
    content: string;
}

const packageJson = {
    name: "app",
    version: "1.0.0",
    private: true,
    dependencies: {},
    devDependencies: {},
    optionalDependencies: {},
    peerDependencies: {},
};

const lockFiles: Record<Pm, VFile[]> = {
    npm: [
        {
            name: "package.json",
            content: JSON.stringify(packageJson, null, 4),
        },
        {
            name: "package-lock.json",
            content: unindent`
            {
                "name": "app",
                "version": "1.0.0",
                "lockfileVersion": 3,
                "requires": true,
                "packages": {
                    "": {
                        "name": "app",
                        "version": "1.0.0"
                    }
                }
            }
        `,
        },
    ],
    pnpm: [
        {
            name: "package.json",
            content: JSON.stringify(packageJson, null, 4),
        },
        {
            name: "pnpm-lock.yaml",
            content: unindent`
            lockfileVersion: '9.0'

            settings:
            autoInstallPeers: true
            excludeLinksFromLockfile: false

            importers:

            .: {}
        `,
        },
    ],
    "yarn-classic": [
        {
            name: "package.json",
            content: JSON.stringify(packageJson, null, 4),
        },
        {
            name: "yarn.lock",
            content: unindent`
            # THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
            # yarn lockfile v1
        `,
        },
    ],
    "yarn-berry": [
        {
            name: "package.json",
            content: JSON.stringify(
                {
                    ...packageJson,
                    packageManager: "yarn@4.0.0",
                },
                null,
                4,
            ),
        },
        {
            name: "yarn.lock",
            content: unindent`
                # This file is generated by running "yarn install" inside your project.
                # Manual changes might be lost - proceed with caution!

                __metadata:
                version: 8
                cacheKey: 10c0

                "yarn-berry@workspace:.":
                version: 0.0.0-use.local
                resolution: "yarn-berry@workspace:."
                languageName: unknown
                linkType: soft
            `,
        },
    ],
    bun: [
        {
            name: "package.json",
            content: JSON.stringify(packageJson, null, 4),
        },
        {
            name: "bun.lock",
            content: unindent`
            {
                "lockfileVersion": 1,
                "configVersion": 1,
                "workspaces": {
                    "": {
                        "name": "bun",
                    },
                },
                "packages": {}
            }
        `,
        },
    ],
};

export class Volume extends BaseVolume {
    constructor(public cwd: string) {
        super();
    }

    mount(pm: Pm) {
        const files = [lockFiles[pm]].flat().map(({ name, content }) => [name, content] as const);
        this.fromJSON(Object.fromEntries(files), this.cwd);

        return this;
    }
}
